---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# nmcs

<!-- badges: start -->
<!-- badges: end -->

The goal of nmcs is to obtain a nested model confidence set (NMCS) and the LogP uncertainty measure for a given shrinkage model selection method.

## Installation

You can install the released version of nmcs from Github with:

``` r
devtools::install_github("YuanyuanLi96/nmcs")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r, warning=FALSE}
library(nmcs)
## basic example code
set.seed(0)
n=100
p=10
B=200
X = matrix(rnorm(n*p),nrow=n,ncol=p)
true_b = c(1:3, rep(0,p-3))
predy = X %*% true_b
#Gaussian
Y=Generate_Y(predy,sigmasq = 1,n=n)
alpha=c(0.05,0.1,0.3)
result=NMCS(Y, X, alpha=alpha,B=B)
output_NMCS(result,alpha=alpha)#NMCS result
result$hat_logP#LogP measure
#Binomial
Y=Generate_Y(predy, n=n, family = "binomial")
result=NMCS(Y, X, family="binomial",alpha=alpha, B=B)
output_NMCS(result,alpha=alpha)#NMCS result
result$hat_logP#LogP measure
#GAM
Xn=X
Xn[,2]=-1/3*X[,1]^3+rnorm(n)
predy_n = Xn %*% true_b
Yn=Generate_Y(predy_n, n=n, family = "gam")
result=NMCS(Yn, Xn, family="gam",alpha=alpha, B=B)
output_NMCS(result,alpha=alpha)#NMCS result
result$hat_logP#LogP measure
```

